### ISSUE TITLE
Complete info about Workshops venue

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#170]
Current status:
http://pycon-beta-2174.rostiapp.cz/2019/venue/#workshops

- [x] Add how to get there info (similar to main venue by means of transport) **required**
- [x] Add info about the building itself (text and/or photo).
- [x] Consider adding a map showing where to go.
- [x] Consider adding video about Faculty.

**Comment by frenzymadness** [comment]
In points:

- Text is ready in a shared document
- Photos are available on google drive and also in google maps
- I would not do that because there are a lot of possibilities (it's a university campus). We'll provide arrows on the way from the tram stop to the building.
- I'd add it there with a note that it's just faculty propagation video but you can see the building from inside in it.
