### ISSUE TITLE
Proposal forms tweaks

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#25]
_this issue was moved from 2018_

# Better order of fields + divide them into 2 sections (their names are TBD)

[Public information]
What’s your name? 
What is the title of your talk? 
Tell the audience about your talk in 1–3 paragraphs (90–200 words) 
Language
Difficulty
Why are you the right person to talk about the topic you chose?
Your photo (not an illustration nor avatar)
Twitter handle 
GitHub username 

[Non-public information]
Got a video? 
Your email address
I need financial aid to make this talk possible
Details about required financial aid 
Anything else you want to tell us?

# Better microcopy

-  _What is the title of your talk?_ and _Tell the audience about your talk in 1–3 paragraphs (90–200 words):_
- _English (preffered)_ => _English (preffered by PyCon CZ)_
- _If you already have a recording of you giving a talk, you can paste the link here._ => _If you have a link to a publicly available recording of you giving a talk. Will be used in the decision process._
- _It will be published on the website. Ideal photo is: a head shot, shows only you, has no “filters” applied and is as large and uncompressed as possible. We might crop it and change contrast, brightness etc. to fit PyCon CZ visual style._ => _Ideal photo is as large (really there's no limit, please no 128 × 128 px, even 1000 × 1000 px isn’t too much) and as uncompressed as possible, is a head shot, doesn’t show other people and has no “filters” applied. We might crop it and change contrast, brightness etc. to fit PyCon CZ visual style._
- Try better to explain what is required for bio.

@hroncok commented on the original issue
> Why are you the right person to talk about the topic you chose?
> Who are you, tel us something about you.
> 
> We could add both questions and than combine the bio used on the website ourselves. We edit all the bios anyway, so this would just give us more material.

**Comment by frenzymadness** [comment]
Ping :wink:

**Comment by veruberu** [comment]
**Mam tu takovy navrh, jestli se vam bude libit**

How to get your talk into PyCon 2019?
console.log("talk " + "you");

We would like to know some essential information to see 
if your proposal is nicely done, thoughts completed and complex 
and if the paper si going to shine in the middle of other proposals!

What’s your name and also your email address:

What is the title of your talk? And Tell the audience about your talk in 1–3 paragraphs (90–200 words)
English (preffered) => English (preffered by PyCon CZ) please:

The presenter is also important for us, so we would like to know something 
about you, do you have @TwitterHandle or are you connected with GitHub? Give us your "username"!

Well, why are you the right person to talk about the topic you choose? We are very exited about making decision
and choose people with passion and because our community is friendly and growing, we would like to know something more, 
we are looking for interesting voices. Do you have any amazing ideas to tell us more about you? Or can you add something
to say about your speech you would like to have on a stage? Tell us:

If you already have a recording of you giving a talk, you can paste the link here. 
Or if you have a link to a publicly available recording of you giving a talk 
you can also paste here: 

It will be published on the website. Ideal photo is: a head shot, shows only you, 
has no “filters” applied and is as large and uncompressed as possible. 
We might crop it and change contrast, brightness etc. to fit PyCon CZ visual style. => Ideal photo is as large 
(really there's no limit, please no 128 × 128 px, even 1000 × 1000 px isn’t too much) 
and as uncompressed as possible, is a head shot, doesn’t show other people and has no “filters” applied. 
We might crop it and change contrast, brightness etc. to fit PyCon CZ visual style.

Do you need some financial aid to make this talk possible?
Take advantage of the open spaces! We are looking for talents and 
we will find a way to help.
Details about required financial aid:

Anything else you want to tell us, any notes, questions? In this case tell us:

**Comment by veruberu** [comment]
upravte si to jak chcete, kdyby jste uvazovali o necem z toho to pouzit..

**Comment by frenzymadness** [comment]
There are a couple of things we need to do before we publish CfP:

**Before we publish CfP**:

- Add a section about Data track
Heading: Data track
Content: This year, for the first time, the teams at PyCon CZ and PyData Prague are joining forces to deliver a data science focussed track at the conference. If we will have enough content related to data science, machine learning, artificial intelligence, etc. we will open a dedicated Data track.
- Publish privacy page
- Add checkbox that submitter accepts our privacy rules and CoC (with links)
- Add timezone info to deadlines

**After we publish it, but ASAP**

- Change button color on the homepage

**Comment by frenzymadness** [comment]
Everything important here is basically done so I'll close this and create a new issue.

**Comment by frenzymadness** [comment]
Put your ideas here: https://github.com/pyvec/cz.pycon.org-2019/issues/46
